"use strict"
try {
    //x = 10;
    miFuncion();
}
catch (error) {
    console.log(error);
}
finally {
    console.log('termina la revision de errores')
}

console.log('continuamos...');